# Generated by Django 5.2 on 2025-04-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_result_exam_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
