# Generated by Django 5.2 on 2025-04-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='answer',
            field=models.CharField(max_length=255),
        ),
    ]
